import type { Metadata } from "next";
import { Finlandica } from "next/font/google";
import "./globals.css";

const font = Finlandica({
  variable: "--font-finlandica",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${font.variable}`}>{children}</body>
    </html>
  );
}
